//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CizgiLogo.logoKargo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="logoKargo.logoKargoSoap")]
    public interface logoKargoSoap {
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/anaKayit", ReplyAction="*")]
        CizgiLogo.logoKargo.anaKayitResponse anaKayit(CizgiLogo.logoKargo.anaKayitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/anaKayit", ReplyAction="*")]
        System.Threading.Tasks.Task<CizgiLogo.logoKargo.anaKayitResponse> anaKayitAsync(CizgiLogo.logoKargo.anaKayitRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/altKayit", ReplyAction="*")]
        CizgiLogo.logoKargo.altKayitResponse altKayit(CizgiLogo.logoKargo.altKayitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/altKayit", ReplyAction="*")]
        System.Threading.Tasks.Task<CizgiLogo.logoKargo.altKayitResponse> altKayitAsync(CizgiLogo.logoKargo.altKayitRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/anaKayitGuncelle", ReplyAction="*")]
        CizgiLogo.logoKargo.anaKayitGuncelleResponse anaKayitGuncelle(CizgiLogo.logoKargo.anaKayitGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/anaKayitGuncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<CizgiLogo.logoKargo.anaKayitGuncelleResponse> anaKayitGuncelleAsync(CizgiLogo.logoKargo.anaKayitGuncelleRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/anaKayitSil", ReplyAction="*")]
        CizgiLogo.logoKargo.anaKayitSilResponse anaKayitSil(CizgiLogo.logoKargo.anaKayitSilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/anaKayitSil", ReplyAction="*")]
        System.Threading.Tasks.Task<CizgiLogo.logoKargo.anaKayitSilResponse> anaKayitSilAsync(CizgiLogo.logoKargo.anaKayitSilRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logoIdAra", ReplyAction="*")]
        CizgiLogo.logoKargo.logoIdAraResponse logoIdAra(CizgiLogo.logoKargo.logoIdAraRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logoIdAra", ReplyAction="*")]
        System.Threading.Tasks.Task<CizgiLogo.logoKargo.logoIdAraResponse> logoIdAraAsync(CizgiLogo.logoKargo.logoIdAraRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logoXmlAktar", ReplyAction="*")]
        CizgiLogo.logoKargo.logoXmlAktarResponse logoXmlAktar(CizgiLogo.logoKargo.logoXmlAktarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logoXmlAktar", ReplyAction="*")]
        System.Threading.Tasks.Task<CizgiLogo.logoKargo.logoXmlAktarResponse> logoXmlAktarAsync(CizgiLogo.logoKargo.logoXmlAktarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class anaKayitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="anaKayit", Namespace="http://tempuri.org/", Order=0)]
        public CizgiLogo.logoKargo.anaKayitRequestBody Body;
        
        public anaKayitRequest() {
        }
        
        public anaKayitRequest(CizgiLogo.logoKargo.anaKayitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class anaKayitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string logoK_toplamTutar;
        
        public anaKayitRequestBody() {
        }
        
        public anaKayitRequestBody(string key, string logoK_toplamTutar) {
            this.key = key;
            this.logoK_toplamTutar = logoK_toplamTutar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class anaKayitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="anaKayitResponse", Namespace="http://tempuri.org/", Order=0)]
        public CizgiLogo.logoKargo.anaKayitResponseBody Body;
        
        public anaKayitResponse() {
        }
        
        public anaKayitResponse(CizgiLogo.logoKargo.anaKayitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class anaKayitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement anaKayitResult;
        
        public anaKayitResponseBody() {
        }
        
        public anaKayitResponseBody(System.Xml.Linq.XElement anaKayitResult) {
            this.anaKayitResult = anaKayitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class altKayitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="altKayit", Namespace="http://tempuri.org/", Order=0)]
        public CizgiLogo.logoKargo.altKayitRequestBody Body;
        
        public altKayitRequest() {
        }
        
        public altKayitRequest(CizgiLogo.logoKargo.altKayitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class altKayitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string logoKargo_arasFatNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string logoKargo_mok;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string logoKargo_musteri;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string logoKargo_tutar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string logoKargo_ToplamTutar;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string logoKargo_teslimTarih;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string logoKargo_takipNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string logoKargo_anaKayit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string logoKargo_odemeTarihi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string logoKargo_tahsilatlitutar;
        
        public altKayitRequestBody() {
        }
        
        public altKayitRequestBody(string key, string logoKargo_arasFatNo, string logoKargo_mok, string logoKargo_musteri, string logoKargo_tutar, string logoKargo_ToplamTutar, string logoKargo_teslimTarih, string logoKargo_takipNo, string logoKargo_anaKayit, string logoKargo_odemeTarihi, string logoKargo_tahsilatlitutar) {
            this.key = key;
            this.logoKargo_arasFatNo = logoKargo_arasFatNo;
            this.logoKargo_mok = logoKargo_mok;
            this.logoKargo_musteri = logoKargo_musteri;
            this.logoKargo_tutar = logoKargo_tutar;
            this.logoKargo_ToplamTutar = logoKargo_ToplamTutar;
            this.logoKargo_teslimTarih = logoKargo_teslimTarih;
            this.logoKargo_takipNo = logoKargo_takipNo;
            this.logoKargo_anaKayit = logoKargo_anaKayit;
            this.logoKargo_odemeTarihi = logoKargo_odemeTarihi;
            this.logoKargo_tahsilatlitutar = logoKargo_tahsilatlitutar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class altKayitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="altKayitResponse", Namespace="http://tempuri.org/", Order=0)]
        public CizgiLogo.logoKargo.altKayitResponseBody Body;
        
        public altKayitResponse() {
        }
        
        public altKayitResponse(CizgiLogo.logoKargo.altKayitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class altKayitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string altKayitResult;
        
        public altKayitResponseBody() {
        }
        
        public altKayitResponseBody(string altKayitResult) {
            this.altKayitResult = altKayitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class anaKayitGuncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="anaKayitGuncelle", Namespace="http://tempuri.org/", Order=0)]
        public CizgiLogo.logoKargo.anaKayitGuncelleRequestBody Body;
        
        public anaKayitGuncelleRequest() {
        }
        
        public anaKayitGuncelleRequest(CizgiLogo.logoKargo.anaKayitGuncelleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class anaKayitGuncelleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string logoK_toplamKayit;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public double logoK_toplamTutar;
        
        public anaKayitGuncelleRequestBody() {
        }
        
        public anaKayitGuncelleRequestBody(string key, int id, string logoK_toplamKayit, double logoK_toplamTutar) {
            this.key = key;
            this.id = id;
            this.logoK_toplamKayit = logoK_toplamKayit;
            this.logoK_toplamTutar = logoK_toplamTutar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class anaKayitGuncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="anaKayitGuncelleResponse", Namespace="http://tempuri.org/", Order=0)]
        public CizgiLogo.logoKargo.anaKayitGuncelleResponseBody Body;
        
        public anaKayitGuncelleResponse() {
        }
        
        public anaKayitGuncelleResponse(CizgiLogo.logoKargo.anaKayitGuncelleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class anaKayitGuncelleResponseBody {
        
        public anaKayitGuncelleResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class anaKayitSilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="anaKayitSil", Namespace="http://tempuri.org/", Order=0)]
        public CizgiLogo.logoKargo.anaKayitSilRequestBody Body;
        
        public anaKayitSilRequest() {
        }
        
        public anaKayitSilRequest(CizgiLogo.logoKargo.anaKayitSilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class anaKayitSilRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id;
        
        public anaKayitSilRequestBody() {
        }
        
        public anaKayitSilRequestBody(string key, string id) {
            this.key = key;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class anaKayitSilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="anaKayitSilResponse", Namespace="http://tempuri.org/", Order=0)]
        public CizgiLogo.logoKargo.anaKayitSilResponseBody Body;
        
        public anaKayitSilResponse() {
        }
        
        public anaKayitSilResponse(CizgiLogo.logoKargo.anaKayitSilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class anaKayitSilResponseBody {
        
        public anaKayitSilResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoIdAraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logoIdAra", Namespace="http://tempuri.org/", Order=0)]
        public CizgiLogo.logoKargo.logoIdAraRequestBody Body;
        
        public logoIdAraRequest() {
        }
        
        public logoIdAraRequest(CizgiLogo.logoKargo.logoIdAraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logoIdAraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int anaKayitID;
        
        public logoIdAraRequestBody() {
        }
        
        public logoIdAraRequestBody(string key, int anaKayitID) {
            this.key = key;
            this.anaKayitID = anaKayitID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoIdAraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logoIdAraResponse", Namespace="http://tempuri.org/", Order=0)]
        public CizgiLogo.logoKargo.logoIdAraResponseBody Body;
        
        public logoIdAraResponse() {
        }
        
        public logoIdAraResponse(CizgiLogo.logoKargo.logoIdAraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logoIdAraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement logoIdAraResult;
        
        public logoIdAraResponseBody() {
        }
        
        public logoIdAraResponseBody(System.Xml.Linq.XElement logoIdAraResult) {
            this.logoIdAraResult = logoIdAraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoXmlAktarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logoXmlAktar", Namespace="http://tempuri.org/", Order=0)]
        public CizgiLogo.logoKargo.logoXmlAktarRequestBody Body;
        
        public logoXmlAktarRequest() {
        }
        
        public logoXmlAktarRequest(CizgiLogo.logoKargo.logoXmlAktarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logoXmlAktarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int anaKayitID;
        
        public logoXmlAktarRequestBody() {
        }
        
        public logoXmlAktarRequestBody(string key, int anaKayitID) {
            this.key = key;
            this.anaKayitID = anaKayitID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoXmlAktarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logoXmlAktarResponse", Namespace="http://tempuri.org/", Order=0)]
        public CizgiLogo.logoKargo.logoXmlAktarResponseBody Body;
        
        public logoXmlAktarResponse() {
        }
        
        public logoXmlAktarResponse(CizgiLogo.logoKargo.logoXmlAktarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logoXmlAktarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string logoXmlAktarResult;
        
        public logoXmlAktarResponseBody() {
        }
        
        public logoXmlAktarResponseBody(string logoXmlAktarResult) {
            this.logoXmlAktarResult = logoXmlAktarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface logoKargoSoapChannel : CizgiLogo.logoKargo.logoKargoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class logoKargoSoapClient : System.ServiceModel.ClientBase<CizgiLogo.logoKargo.logoKargoSoap>, CizgiLogo.logoKargo.logoKargoSoap {
        
        public logoKargoSoapClient() {
        }
        
        public logoKargoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public logoKargoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public logoKargoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public logoKargoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CizgiLogo.logoKargo.anaKayitResponse CizgiLogo.logoKargo.logoKargoSoap.anaKayit(CizgiLogo.logoKargo.anaKayitRequest request) {
            return base.Channel.anaKayit(request);
        }
        
        public System.Xml.Linq.XElement anaKayit(string key, string logoK_toplamTutar) {
            CizgiLogo.logoKargo.anaKayitRequest inValue = new CizgiLogo.logoKargo.anaKayitRequest();
            inValue.Body = new CizgiLogo.logoKargo.anaKayitRequestBody();
            inValue.Body.key = key;
            inValue.Body.logoK_toplamTutar = logoK_toplamTutar;
            CizgiLogo.logoKargo.anaKayitResponse retVal = ((CizgiLogo.logoKargo.logoKargoSoap)(this)).anaKayit(inValue);
            return retVal.Body.anaKayitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CizgiLogo.logoKargo.anaKayitResponse> CizgiLogo.logoKargo.logoKargoSoap.anaKayitAsync(CizgiLogo.logoKargo.anaKayitRequest request) {
            return base.Channel.anaKayitAsync(request);
        }
        
        public System.Threading.Tasks.Task<CizgiLogo.logoKargo.anaKayitResponse> anaKayitAsync(string key, string logoK_toplamTutar) {
            CizgiLogo.logoKargo.anaKayitRequest inValue = new CizgiLogo.logoKargo.anaKayitRequest();
            inValue.Body = new CizgiLogo.logoKargo.anaKayitRequestBody();
            inValue.Body.key = key;
            inValue.Body.logoK_toplamTutar = logoK_toplamTutar;
            return ((CizgiLogo.logoKargo.logoKargoSoap)(this)).anaKayitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CizgiLogo.logoKargo.altKayitResponse CizgiLogo.logoKargo.logoKargoSoap.altKayit(CizgiLogo.logoKargo.altKayitRequest request) {
            return base.Channel.altKayit(request);
        }
        
        public string altKayit(string key, string logoKargo_arasFatNo, string logoKargo_mok, string logoKargo_musteri, string logoKargo_tutar, string logoKargo_ToplamTutar, string logoKargo_teslimTarih, string logoKargo_takipNo, string logoKargo_anaKayit, string logoKargo_odemeTarihi, string logoKargo_tahsilatlitutar) {
            CizgiLogo.logoKargo.altKayitRequest inValue = new CizgiLogo.logoKargo.altKayitRequest();
            inValue.Body = new CizgiLogo.logoKargo.altKayitRequestBody();
            inValue.Body.key = key;
            inValue.Body.logoKargo_arasFatNo = logoKargo_arasFatNo;
            inValue.Body.logoKargo_mok = logoKargo_mok;
            inValue.Body.logoKargo_musteri = logoKargo_musteri;
            inValue.Body.logoKargo_tutar = logoKargo_tutar;
            inValue.Body.logoKargo_ToplamTutar = logoKargo_ToplamTutar;
            inValue.Body.logoKargo_teslimTarih = logoKargo_teslimTarih;
            inValue.Body.logoKargo_takipNo = logoKargo_takipNo;
            inValue.Body.logoKargo_anaKayit = logoKargo_anaKayit;
            inValue.Body.logoKargo_odemeTarihi = logoKargo_odemeTarihi;
            inValue.Body.logoKargo_tahsilatlitutar = logoKargo_tahsilatlitutar;
            CizgiLogo.logoKargo.altKayitResponse retVal = ((CizgiLogo.logoKargo.logoKargoSoap)(this)).altKayit(inValue);
            return retVal.Body.altKayitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CizgiLogo.logoKargo.altKayitResponse> CizgiLogo.logoKargo.logoKargoSoap.altKayitAsync(CizgiLogo.logoKargo.altKayitRequest request) {
            return base.Channel.altKayitAsync(request);
        }
        
        public System.Threading.Tasks.Task<CizgiLogo.logoKargo.altKayitResponse> altKayitAsync(string key, string logoKargo_arasFatNo, string logoKargo_mok, string logoKargo_musteri, string logoKargo_tutar, string logoKargo_ToplamTutar, string logoKargo_teslimTarih, string logoKargo_takipNo, string logoKargo_anaKayit, string logoKargo_odemeTarihi, string logoKargo_tahsilatlitutar) {
            CizgiLogo.logoKargo.altKayitRequest inValue = new CizgiLogo.logoKargo.altKayitRequest();
            inValue.Body = new CizgiLogo.logoKargo.altKayitRequestBody();
            inValue.Body.key = key;
            inValue.Body.logoKargo_arasFatNo = logoKargo_arasFatNo;
            inValue.Body.logoKargo_mok = logoKargo_mok;
            inValue.Body.logoKargo_musteri = logoKargo_musteri;
            inValue.Body.logoKargo_tutar = logoKargo_tutar;
            inValue.Body.logoKargo_ToplamTutar = logoKargo_ToplamTutar;
            inValue.Body.logoKargo_teslimTarih = logoKargo_teslimTarih;
            inValue.Body.logoKargo_takipNo = logoKargo_takipNo;
            inValue.Body.logoKargo_anaKayit = logoKargo_anaKayit;
            inValue.Body.logoKargo_odemeTarihi = logoKargo_odemeTarihi;
            inValue.Body.logoKargo_tahsilatlitutar = logoKargo_tahsilatlitutar;
            return ((CizgiLogo.logoKargo.logoKargoSoap)(this)).altKayitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CizgiLogo.logoKargo.anaKayitGuncelleResponse CizgiLogo.logoKargo.logoKargoSoap.anaKayitGuncelle(CizgiLogo.logoKargo.anaKayitGuncelleRequest request) {
            return base.Channel.anaKayitGuncelle(request);
        }
        
        public void anaKayitGuncelle(string key, int id, string logoK_toplamKayit, double logoK_toplamTutar) {
            CizgiLogo.logoKargo.anaKayitGuncelleRequest inValue = new CizgiLogo.logoKargo.anaKayitGuncelleRequest();
            inValue.Body = new CizgiLogo.logoKargo.anaKayitGuncelleRequestBody();
            inValue.Body.key = key;
            inValue.Body.id = id;
            inValue.Body.logoK_toplamKayit = logoK_toplamKayit;
            inValue.Body.logoK_toplamTutar = logoK_toplamTutar;
            CizgiLogo.logoKargo.anaKayitGuncelleResponse retVal = ((CizgiLogo.logoKargo.logoKargoSoap)(this)).anaKayitGuncelle(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CizgiLogo.logoKargo.anaKayitGuncelleResponse> CizgiLogo.logoKargo.logoKargoSoap.anaKayitGuncelleAsync(CizgiLogo.logoKargo.anaKayitGuncelleRequest request) {
            return base.Channel.anaKayitGuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<CizgiLogo.logoKargo.anaKayitGuncelleResponse> anaKayitGuncelleAsync(string key, int id, string logoK_toplamKayit, double logoK_toplamTutar) {
            CizgiLogo.logoKargo.anaKayitGuncelleRequest inValue = new CizgiLogo.logoKargo.anaKayitGuncelleRequest();
            inValue.Body = new CizgiLogo.logoKargo.anaKayitGuncelleRequestBody();
            inValue.Body.key = key;
            inValue.Body.id = id;
            inValue.Body.logoK_toplamKayit = logoK_toplamKayit;
            inValue.Body.logoK_toplamTutar = logoK_toplamTutar;
            return ((CizgiLogo.logoKargo.logoKargoSoap)(this)).anaKayitGuncelleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CizgiLogo.logoKargo.anaKayitSilResponse CizgiLogo.logoKargo.logoKargoSoap.anaKayitSil(CizgiLogo.logoKargo.anaKayitSilRequest request) {
            return base.Channel.anaKayitSil(request);
        }
        
        public void anaKayitSil(string key, string id) {
            CizgiLogo.logoKargo.anaKayitSilRequest inValue = new CizgiLogo.logoKargo.anaKayitSilRequest();
            inValue.Body = new CizgiLogo.logoKargo.anaKayitSilRequestBody();
            inValue.Body.key = key;
            inValue.Body.id = id;
            CizgiLogo.logoKargo.anaKayitSilResponse retVal = ((CizgiLogo.logoKargo.logoKargoSoap)(this)).anaKayitSil(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CizgiLogo.logoKargo.anaKayitSilResponse> CizgiLogo.logoKargo.logoKargoSoap.anaKayitSilAsync(CizgiLogo.logoKargo.anaKayitSilRequest request) {
            return base.Channel.anaKayitSilAsync(request);
        }
        
        public System.Threading.Tasks.Task<CizgiLogo.logoKargo.anaKayitSilResponse> anaKayitSilAsync(string key, string id) {
            CizgiLogo.logoKargo.anaKayitSilRequest inValue = new CizgiLogo.logoKargo.anaKayitSilRequest();
            inValue.Body = new CizgiLogo.logoKargo.anaKayitSilRequestBody();
            inValue.Body.key = key;
            inValue.Body.id = id;
            return ((CizgiLogo.logoKargo.logoKargoSoap)(this)).anaKayitSilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CizgiLogo.logoKargo.logoIdAraResponse CizgiLogo.logoKargo.logoKargoSoap.logoIdAra(CizgiLogo.logoKargo.logoIdAraRequest request) {
            return base.Channel.logoIdAra(request);
        }
        
        public System.Xml.Linq.XElement logoIdAra(string key, int anaKayitID) {
            CizgiLogo.logoKargo.logoIdAraRequest inValue = new CizgiLogo.logoKargo.logoIdAraRequest();
            inValue.Body = new CizgiLogo.logoKargo.logoIdAraRequestBody();
            inValue.Body.key = key;
            inValue.Body.anaKayitID = anaKayitID;
            CizgiLogo.logoKargo.logoIdAraResponse retVal = ((CizgiLogo.logoKargo.logoKargoSoap)(this)).logoIdAra(inValue);
            return retVal.Body.logoIdAraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CizgiLogo.logoKargo.logoIdAraResponse> CizgiLogo.logoKargo.logoKargoSoap.logoIdAraAsync(CizgiLogo.logoKargo.logoIdAraRequest request) {
            return base.Channel.logoIdAraAsync(request);
        }
        
        public System.Threading.Tasks.Task<CizgiLogo.logoKargo.logoIdAraResponse> logoIdAraAsync(string key, int anaKayitID) {
            CizgiLogo.logoKargo.logoIdAraRequest inValue = new CizgiLogo.logoKargo.logoIdAraRequest();
            inValue.Body = new CizgiLogo.logoKargo.logoIdAraRequestBody();
            inValue.Body.key = key;
            inValue.Body.anaKayitID = anaKayitID;
            return ((CizgiLogo.logoKargo.logoKargoSoap)(this)).logoIdAraAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CizgiLogo.logoKargo.logoXmlAktarResponse CizgiLogo.logoKargo.logoKargoSoap.logoXmlAktar(CizgiLogo.logoKargo.logoXmlAktarRequest request) {
            return base.Channel.logoXmlAktar(request);
        }
        
        public string logoXmlAktar(string key, int anaKayitID) {
            CizgiLogo.logoKargo.logoXmlAktarRequest inValue = new CizgiLogo.logoKargo.logoXmlAktarRequest();
            inValue.Body = new CizgiLogo.logoKargo.logoXmlAktarRequestBody();
            inValue.Body.key = key;
            inValue.Body.anaKayitID = anaKayitID;
            CizgiLogo.logoKargo.logoXmlAktarResponse retVal = ((CizgiLogo.logoKargo.logoKargoSoap)(this)).logoXmlAktar(inValue);
            return retVal.Body.logoXmlAktarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CizgiLogo.logoKargo.logoXmlAktarResponse> CizgiLogo.logoKargo.logoKargoSoap.logoXmlAktarAsync(CizgiLogo.logoKargo.logoXmlAktarRequest request) {
            return base.Channel.logoXmlAktarAsync(request);
        }
        
        public System.Threading.Tasks.Task<CizgiLogo.logoKargo.logoXmlAktarResponse> logoXmlAktarAsync(string key, int anaKayitID) {
            CizgiLogo.logoKargo.logoXmlAktarRequest inValue = new CizgiLogo.logoKargo.logoXmlAktarRequest();
            inValue.Body = new CizgiLogo.logoKargo.logoXmlAktarRequestBody();
            inValue.Body.key = key;
            inValue.Body.anaKayitID = anaKayitID;
            return ((CizgiLogo.logoKargo.logoKargoSoap)(this)).logoXmlAktarAsync(inValue);
        }
    }
}
